name: mdp
description: MDP developed within Nexton Company.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Smart project structure with dependency injection and route management
  flutter_modular: ^2.0.0+1

  # Adds support for google fonts
  google_fonts: ^1.1.0

  # Package to handle dynamic String & Json interpolation.
  interpolation: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # Provides internationalization and localization facilities
  intl: ^0.17.0

  # A package for fontAwesome Icons.
  font_awesome_flutter: ^8.10.0

  # http package for connection.
  http: ^0.12.2

  # Powerful Http client for Dart
  dio: ^3.0.10
  pretty_dio_logger: ^1.1.1

  syncfusion_flutter_calendar: ^19.1.56

  # Allow acces to streamBuilder
  rxdart: ^0.24.1

  # Providing a persistent store for simple data.
  shared_preferences: ^2.0.5

  change_app_package_name: ^1.0.0

  # package for synchronizing with native user mobile calendar.
  device_calendar: ^3.1.0

  # package for splashScreen.
  splashscreen: ^1.3.5

  # package for radio buttons.
  group_radio_button: ^1.0.1

  # package for bottom sheets.
  modal_bottom_sheet: ^2.0.0

  # photo view library.
  photo_view: ^0.11.1

  # map launcher library.
  map_launcher: ^2.0.0

  # tabBar library.
  contained_tab_bar_view: ^0.8.0

  # user geolocator package.
  geolocator: ^7.0.3

  # package to get address from position lat and long.
  geocoding: ^2.0.0

  # toast for flutter.
  fluttertoast: ^8.0.6

  # package to make phone calls.
  url_launcher: ^6.0.3

  # package for emailValidation.
  email_validator: ^2.0.1

  # package for svg.
  flutter_svg: ^0.22.0

  # package for rating stars.
  flutter_rating_bar: ^4.0.0

  # package dropdown.
  dropdown_search: ^0.6.1

  dotted_border: ^2.0.0

  # package for getting path of assets.
  flutter_absolute_path: ^1.0.6

  # package for picking multiple images or picture from camera.
  multi_image_picker: ^4.8.1

  # package for autocomplete textfield.
  flutter_typeahead: ^3.2.0

  # package for drawing signature.
  signature: ^4.1.1

  # package for downloading files.
  flutter_downloader: ^1.6.1

  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2

  # package for flushbar a toast with animation.
  another_flushbar: ^1.10.24

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lang/
    - assets/fonts/

fonts:
  - family: UniformRounded
    fonts:
      - asset: assets/fonts/Uniform-Rounded.ttf
        weight: 400

  - family: roboto
    fonts:
      - asset: assets/fonts/Roboto-Thin.ttf
        weight: 100
      - asset: assets/fonts/Roboto-Regular.ttf
        weight: 400
      - asset: assets/fonts/Roboto-Italic.ttf
        style: italic
        weight: 500
      - asset: assets/fonts/Roboto-Medium.ttf
        weight: 500
      - asset: assets/fonts/Roboto-Bold.ttf
        weight: 700
      - asset: assets/fonts/Roboto-Black.ttf
        weight: 900